services:
  - type: web
    name: esgi-cloud-exam-2-32430
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: esgi-cloud-exam-2-db-32430
          property: connectionString

databases:
  - name: esgi-cloud-exam-2-db-32430
    region: frankfurt
    plan: free
